language: python
python:
  - "2.7"

sudo: false
cache: pip

install: pip install -r requirements.txt
script: sphinx-build -nWT -b dummy source build

after_success:
  - chmod +x ./publish.sh
  - ./publish.sh
